modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "vr_interactions"
version = "${version}"
displayName = "VR Interactions"
authors = "demistorm"
description = '''
A collection of various enhancements to the core gameplay of VR Minecraft.
'''

[[mixins]]
config = "vr_interactions.mixins.json"

[[dependencies.vr_interactions]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_interactions]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

# Optional Vivecraft Dependency
[[dependencies.vr_interactions]]
modId = "vivecraft"
mandatory = false
versionRange = "[1.3.3,)"
ordering = "NONE"
side = "BOTH"
